parameters:
    pim_enrich.doctrine.counter.category_registry.class: Pim\Bundle\EnrichBundle\Doctrine\Counter\CategoryItemsCounterRegistry

services:
    pim_enrich.doctrine.counter.category_registry:
        class: '%pim_enrich.doctrine.counter.category_registry.class%'
