services:
    pim_catalog.repository.attribute_group:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeGroupRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute_group.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.attribute:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.family:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\FamilyRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.family_variant:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\FamilyVariantRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family_variant.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.attribute_requirement:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeRequirementRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute_requirement.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.attribute_option:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeOptionRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute_option.class%']
        tags:
            - { name: 'pim_repository' }

    ### Intenal API
    pim_enrich.repository.attribute:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\InternalApi\AttributeGroupRepository'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.attribute.class%'
